name: Build Eleventy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"
  repository_dispatch:
    types: [feed-update-detected]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Push Deploy
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Rebuild on push"

      - name: Scheduled Deploy
        if: ${{ github.event_name == 'schedule' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Scheduled rebuild"

      - name: Triggered Deploy
        if: ${{ github.event_name == 'repository_dispatch' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Triggered rebuild: ${{ github.event.client_payload.reason }}"
